#+title: Readme

* Introduction
This tool maps aliases, previous or withdrawn symbols to current approved HGNC symbols. Checks for any entries that are not gene symbols and fixes capitalizations. Ensembl and RefSeq annotation files sometimes use previous or alias symbols. This tool also checks Ensembl and NCBI annotation files for different genome versions and shows which gene symbol is used. This way a more appropriate gene set can be used to avoid the false negatives in the variant discovery process.

* How to install

Clone this repo to install.

~git clone https://github.com/barslmn/bioscripts~

To get the most up to date annotation files run the ~./INSTALL.sh~. This process takes some time as it downloads various gene symbol annotation files from NCBI and Ensembl and HGNC. Check install section at [[file:genesymbolchecker.org][genesymbolchecker.org]] to see what is being downloaded.

* How to use
Main operation is performed at ~genesymbolchecker.sh~ this file takes a single symbol as its input and returns the status of all of the approved, alias, previous or withdrawn symbols in all available annotation sources.
Another script is ~checkgeneset.sh~ which takes one or more gene and target assembly as its arguments. This script is a wrapper around genesymbolchecker and parses its output.
